# Generated by Django 5.2.4 on 2025-07-29 12:12

import contacts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("contact", models.CharField(max_length=13)),
                ("alternate_contact", models.CharField(blank=True, max_length=13)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "alternate_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("family", "Family"),
                            ("friend", "Friend"),
                            ("work", "Work"),
                            ("client", "Client"),
                            ("vendor", "Vendor"),
                            ("emergency", "Emergency"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_communication",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phone", "Phone Call"),
                            ("email", "Email"),
                            ("sms", "SMS/Text"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("zoom", "Zoom"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=30)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=75)),
                ("state", models.CharField(max_length=75)),
                ("country", models.CharField(max_length=75)),
                ("postal_code", models.CharField(max_length=20)),
                ("linkedin_username", models.CharField(blank=True, max_length=50)),
                ("twitter_username", models.CharField(blank=True, max_length=50)),
                ("facebook_username", models.CharField(blank=True, max_length=50)),
                ("instagram_username", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "contact_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=contacts.models.rename_contact_image,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
